import type { Canvas } from "@/types/canvas";

export const CANVAS_TEMPLATE_MOCKS: Canvas[] = [
  {
    id: "canvas-1",
    name: "Price Tag",
    frameSize: { width: 8.5 * 96, height: 11 * 96 },
    frameBackgroundColor: "#fff",
    layers: [
      {
        name: "Image",
        parentStyle: {},
        contentStyle: {},
        type: "image",
        id: "image-1765285508868-uc83sr8j5",
        value:
          "https://firebasestorage.googleapis.com/v0/b/next-rms.appspot.com/o/workspace%2Famericanfurnituredesign%2Flogo.png?alt=media&token=b69ad58d-29dd-4516-81bc-feb713e0f241",
        cssVars: {
          "--width": "720px",
          "--height": "104px",
          "--background-color": "",
          "--object-fit": "contain",
        },
        transform: {
          translate: [48, 28.7492],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "Frame",
        parentStyle: {},
        contentStyle: {},
        type: "frame",
        id: "frame-1765285554452-nqy4cy7hf",
        cssVars: {
          "--width": "720px",
          "--height": "128px",
          "--background-color": "#1e3681",
        },
        transform: {
          translate: [48, 130.7],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "Input",
        parentStyle: {},
        contentStyle: {},
        type: "input",
        id: "input-1765285587118-f58z80uei",
        value: "1 PC Set",
        cssVars: {
          "--width": "720px",
          "--height": "128px",
          "--font-size": "48px",
          "--font-weight": "900",
          "--padding-top": "12px",
          "--padding-bottom": "12px",
          "--padding-left": "16px",
          "--padding-right": "16px",
          "--align-items": "center",
          "--text-align": "center",
          "--color": "#ffffff",
        },
        transform: {
          translate: [48, 130.7],
          rotate: 0,
          scale: [1, 1],
        },
        data: {
          placeholder: "# PC SET",
          multiLine: false,
          defaultValue: "Great Deal!",
        },
        locked: true,
      },
      {
        name: "Frame",
        parentStyle: {},
        contentStyle: {},
        type: "frame",
        id: "frame-1765286165956-j8viznxsr",
        cssVars: {
          "--width": "720px",
          "--height": "6px",
          "--background-color": "#efefef",
        },
        transform: {
          translate: [48, 473.943],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "Text",
        parentStyle: {},
        contentStyle: {},
        type: "text",
        id: "text-1765286135289-3cpxjfukz",
        value: "Sample Product",
        cssVars: {
          "--width": "720px",
          "--height": "82px",
          "--font-size": "48px",
          "--font-weight": "400",
          "--text-align": "center",
        },
        transform: {
          translate: [48, 258.7],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "Text",
        parentStyle: {},
        contentStyle: {},
        type: "text",
        id: "text-1765286196890-me9f4w090",
        value: "$1,000",
        cssVars: {
          "--width": "720px",
          "--height": "166px",
          "--font-size": "120px",
          "--font-weight": "700",
          "--color": "#e12426",
          "--text-align": "center",
        },
        transform: {
          translate: [48, 335.1],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        visible: true,
        locked: true,
      },
      {
        name: "Frame (Copy)",
        parentStyle: {},
        contentStyle: {},
        type: "frame",
        id: "frame-1765286240347-nrhpuhc9p",
        cssVars: {
          "--width": "720px",
          "--height": "6px",
          "--background-color": "#efefef",
        },
        transform: {
          translate: [48, 951.337],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "User",
        parentStyle: {},
        contentStyle: {},
        type: "user",
        id: "user-1765286253372-zgkyrxeh8",
        value:
          '{"id":"user-1","name":"John Doe","email":"john.doe@example.com"}',
        cssVars: {
          "--width": "211px",
          "--height": "42px",
        },
        transform: {
          translate: [48, 966],
          rotate: 0,
          scale: [1, 1],
        },
        data: {
          displayStyle: "profile",
          size: "x-small",
        },
        locked: true,
      },
      {
        name: "Today's Date",
        parentStyle: {},
        contentStyle: {},
        type: "todays-date",
        id: "todays-date-1765286279139-yprn5bhsc",
        value: "MM/dd/yyyy",
        cssVars: {
          "--width": "509px",
          "--height": "20px",
          "--font-size": "12px",
          "--font-weight": "600",
          "--color": "#8f8f8f",
          "--text-align": "right",
        },
        transform: {
          translate: [259, 988],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "Text",
        parentStyle: {},
        contentStyle: {},
        type: "text",
        id: "text-1765286309444-2xcc07mfz",
        value: "SKU: 123",
        cssVars: {
          "--width": "509px",
          "--height": "21px",
          "--font-size": "12px",
          "--font-weight": "600",
          "--color": "#919191",
          "--text-align": "right",
        },
        transform: {
          translate: [259, 967],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "Products",
        parentStyle: {},
        contentStyle: {},
        type: "product",
        id: "product-1765286357811-2qjv8t43q",
        cssVars: {
          "--width": "720px",
          "--height": "474px",
        },
        transform: {
          translate: [48, 480.3],
          rotate: 0,
          scale: [1, 1],
        },
        data: {
          displayStyle: "list",
          products: [
            {
              id: "1",
              name: "Premium Coffee Beans",
              sku: "COFFEE-001",
              price: 24.99,
              image:
                "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=300",
            },
            {
              id: "2",
              name: "Organic Green Tea",
              sku: "TEA-002",
              price: 18.5,
              image:
                "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=300",
            },
            {
              id: "3",
              name: "Dark Chocolate Bar",
              sku: "CHOC-003",
              price: 8.99,
              image:
                "https://images.unsplash.com/photo-1511381939415-e44015466834?w=300",
            },
          ],
        },
        locked: true,
      },
    ],
  },
  {
    id: "canvas-2",
    name: "Price Tag 2",
    frameSize: { width: 8.5 * 96, height: 11 * 96 },
    frameBackgroundColor: "#fff",
    layers: [
      {
        name: "Image",
        parentStyle: {},
        contentStyle: {},
        type: "image",
        id: "image-1765285508868-uc83sr8j5",
        value:
          "https://firebasestorage.googleapis.com/v0/b/next-rms.appspot.com/o/workspace%2Famericanfurnituredesign%2Flogo.png?alt=media&token=b69ad58d-29dd-4516-81bc-feb713e0f241",
        cssVars: {
          "--width": "720px",
          "--height": "104px",
          "--background-color": "",
          "--object-fit": "contain",
        },
        transform: {
          translate: [48, 28.7492],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "Frame",
        parentStyle: {},
        contentStyle: {},
        type: "frame",
        id: "frame-1765285554452-nqy4cy7hf",
        cssVars: {
          "--width": "720px",
          "--height": "128px",
          "--background-color": "#1e3681",
        },
        transform: {
          translate: [48, 130.7],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "Input",
        parentStyle: {},
        contentStyle: {},
        type: "input",
        id: "input-1765285587118-f58z80uei",
        value: "1 PC Set",
        cssVars: {
          "--width": "720px",
          "--height": "128px",
          "--font-size": "76px",
          "--font-weight": "900",
          "--padding-top": "12px",
          "--padding-bottom": "12px",
          "--padding-left": "16px",
          "--padding-right": "16px",
          "--align-items": "center",
          "--text-align": "center",
          "--color": "#ffffff",
        },
        transform: {
          translate: [48, 130.7],
          rotate: 0,
          scale: [1, 1],
        },
        data: {
          placeholder: "# PC SET",
          multiLine: false,
          defaultValue: "Great Deal!",
        },
        locked: true,
      },
      {
        name: "Frame",
        parentStyle: {},
        contentStyle: {},
        type: "frame",
        id: "frame-1765286165956-j8viznxsr",
        cssVars: {
          "--width": "720px",
          "--height": "6px",
          "--background-color": "#efefef",
        },
        transform: {
          translate: [48, 473.943],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "Text",
        parentStyle: {},
        contentStyle: {},
        type: "text",
        id: "text-1765286135289-3cpxjfukz",
        value: "Sample Product",
        cssVars: {
          "--width": "720px",
          "--height": "82px",
          "--font-size": "48px",
          "--font-weight": "400",
          "--text-align": "center",
        },
        transform: {
          translate: [48, 258.7],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "Text",
        parentStyle: {},
        contentStyle: {},
        type: "text",
        id: "text-1765286196890-me9f4w090",
        value: "$1,000",
        cssVars: {
          "--width": "720px",
          "--height": "166px",
          "--font-size": "120px",
          "--font-weight": "700",
          "--color": "#e12426",
          "--text-align": "center",
          "--font-family": "Fira Code",
        },
        transform: {
          translate: [48, 335.1],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        visible: true,
        locked: true,
      },
      {
        name: "Frame (Copy)",
        parentStyle: {},
        contentStyle: {},
        type: "frame",
        id: "frame-1765286240347-nrhpuhc9p",
        cssVars: {
          "--width": "720px",
          "--height": "6px",
          "--background-color": "#efefef",
        },
        transform: {
          translate: [48, 951.337],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "User",
        parentStyle: {},
        contentStyle: {},
        type: "user",
        id: "user-1765286253372-zgkyrxeh8",
        value:
          '{"id":"user-1","name":"John Doe","email":"john.doe@example.com"}',
        cssVars: {
          "--width": "211px",
          "--height": "42px",
        },
        transform: {
          translate: [48, 966],
          rotate: 0,
          scale: [1, 1],
        },
        data: {
          displayStyle: "profile",
          size: "x-small",
        },
        locked: true,
      },
      {
        name: "Today's Date",
        parentStyle: {},
        contentStyle: {},
        type: "todays-date",
        id: "todays-date-1765286279139-yprn5bhsc",
        value: "MM/dd/yyyy",
        cssVars: {
          "--width": "509px",
          "--height": "20px",
          "--font-size": "12px",
          "--font-weight": "600",
          "--color": "#8f8f8f",
          "--text-align": "right",
        },
        transform: {
          translate: [259, 988],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "Text",
        parentStyle: {},
        contentStyle: {},
        type: "text",
        id: "text-1765286309444-2xcc07mfz",
        value: "SKU: 123",
        cssVars: {
          "--width": "509px",
          "--height": "21px",
          "--font-size": "12px",
          "--font-weight": "600",
          "--color": "#919191",
          "--text-align": "right",
        },
        transform: {
          translate: [259, 967],
          rotate: 0,
          scale: [1, 1],
        },
        data: {},
        locked: true,
      },
      {
        name: "Products",
        parentStyle: {},
        contentStyle: {},
        type: "product",
        id: "product-1765286357811-2qjv8t43q",
        cssVars: {
          "--width": "720px",
          "--height": "474px",
          "--padding-top": "12px",
          "--padding-right": "12px",
          "--padding-bottom": "12px",
          "--padding-left": "12px",
        },
        transform: {
          translate: [48, 480.3],
          rotate: 0,
          scale: [1, 1],
        },
        data: {
          displayStyle: "custom",
          products: [
            {
              id: "1",
              name: "Premium Coffee Beans",
              sku: "COFFEE-001",
              price: 24.99,
              image:
                "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=300",
            },
            {
              id: "2",
              name: "Organic Green Tea",
              sku: "TEA-002",
              price: 18.5,
              image:
                "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=300",
            },
            {
              id: "3",
              name: "Dark Chocolate Bar",
              sku: "CHOC-003",
              price: 8.99,
              image:
                "https://images.unsplash.com/photo-1511381939415-e44015466834?w=300",
            },
          ],
          customDesign: {
            layers: [
              {
                name: "Product Image",
                parentStyle: {},
                contentStyle: {},
                type: "product-image",
                id: "product-image-1765918205125-ngu0aie22",
                cssVars: {
                  "--width": "100px",
                  "--height": "100px",
                  "--border-top-left-radius": "12px",
                  "--border-top-right-radius": "12px",
                  "--border-bottom-right-radius": "12px",
                  "--border-bottom-left-radius": "12px",
                },
                transform: {
                  translate: [0, 0],
                  rotate: 0,
                  scale: [1, 1],
                },
                data: {},
              },
              {
                name: "Product QR Code",
                parentStyle: {},
                contentStyle: {},
                type: "product-qrcode",
                id: "product-qrcode-1765918213459-dmu3rqdto",
                value: "www.google.com/search?q=@product.sku",
                cssVars: {
                  "--width": "100px",
                  "--height": "100px",
                  "--background-color": "#ffffff",
                },
                transform: {
                  translate: [596, 0],
                  rotate: 0,
                  scale: [1, 1],
                },
                data: {
                  qrLevel: "M",
                  qrFgColor: "#000000",
                },
              },
              {
                name: "Product Name",
                parentStyle: {},
                contentStyle: {},
                type: "product-name",
                id: "product-name-1765918218307-cylyz7kd4",
                cssVars: {
                  "--width": "469px",
                  "--height": "41px",
                  "--font-size": "24px",
                  "--font-weight": "900",
                },
                transform: {
                  translate: [111.4, 8.8672],
                  rotate: 0,
                  scale: [1, 1],
                },
                data: {},
              },
              {
                name: "Product SKU",
                parentStyle: {},
                contentStyle: {},
                type: "product-sku",
                id: "product-sku-1765918224356-vq3u80hjf",
                cssVars: {
                  "--width": "469px",
                  "--height": "20px",
                  "--font-size": "14px",
                  "--font-weight": "400",
                  "--color": "#9ca3af",
                  "--font-family": "Satisfy",
                },
                transform: {
                  translate: [111.381, 50.1364],
                  rotate: 0,
                  scale: [1, 1],
                },
                data: {},
              },
            ],
            frameSize: {
              width: 696,
              height: 100,
            },
            frameBackgroundColor: "#ffffff",
          },
        },
        locked: true,
      },
    ],
  },
];

export const CANVAS_DESIGN_MOCKS: Canvas[] = [];
