import { DIACRITIC_DARK_COLOR, LETTER_DARK_COLOR } from "@/config"
import * as React from "react"

const SVGComponent = (props: React.ComponentProps<"svg">) => {
  const styles = `
    .codecanon-letter { fill: var(--color-codecanon-letter, var(--color-codecanon-primary, ${LETTER_DARK_COLOR})); }
    .codecanon-diacritic { fill: var(--color-codecanon-diacritic, var(--color-codecanon-secondary, ${DIACRITIC_DARK_COLOR})); }
  `

  return (
    <svg
      viewBox="0 0 1600 896"
      xmlns="http://www.w3.org/2000/svg"
      height="24px"
      {...props}
    >
      <defs>
        <style dangerouslySetInnerHTML={{ __html: styles }} />
      </defs>
      <rect
        className="codecanon-letter"
        width={148.6}
        height={36}
        x={89.6}
        y={338}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={223}
        x={89.6}
        y={338}
      />
      <rect
        className="codecanon-letter"
        width={148.6}
        height={36}
        x={89.6}
        y={525.1}
      />
      <rect
        className="codecanon-letter"
        width={148.6}
        height={36}
        x={254.3}
        y={393.5}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={167.5}
        x={254.3}
        y={393.5}
      />
      <rect
        className="codecanon-letter"
        width={147.3}
        height={39.1}
        x={255.7}
        y={522}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={167.5}
        x={365.8}
        y={393.5}
      />
      <rect
        className="codecanon-diacritic"
        width={42.3}
        height={39.8}
        x={275.6}
        y={343.8}
      />
      <rect
        className="codecanon-diacritic"
        width={42.3}
        height={39.8}
        x={339.5}
        y={343.8}
      />
      <rect
        className="codecanon-letter"
        width={147.8}
        height={36}
        x={419.3}
        y={393.5}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={167.5}
        x={419.3}
        y={393.5}
      />
      <rect
        className="codecanon-letter"
        width={146.4}
        height={39.1}
        x={420.7}
        y={522}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={225.3}
        x={530}
        y={335.8}
      />
      <rect
        className="codecanon-letter"
        width={119.7}
        height={29.9}
        x={583.1}
        y={393.5}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={167.5}
        x={583.1}
        y={393.5}
      />
      <rect
        className="codecanon-letter"
        width={119.7}
        height={36}
        x={583.1}
        y={525.1}
      />
      <rect
        className="codecanon-letter"
        width={119.7}
        height={29.9}
        x={583.1}
        y={464.6}
      />
      <rect
        className="codecanon-letter"
        width={36.4}
        height={98}
        x={666.5}
        y={395.8}
      />
      <rect
        className="codecanon-diacritic"
        width={42.3}
        height={39.8}
        x={621.9}
        y={343.8}
      />
      <rect
        className="codecanon-letter"
        width={148.6}
        height={36}
        x={719.2}
        y={338}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={223}
        x={719.1}
        y={338}
      />
      <rect
        className="codecanon-letter"
        width={148.6}
        height={36}
        x={719.2}
        y={525.1}
      />
      <rect
        className="codecanon-letter"
        width={148.2}
        height={33.4}
        x={885.3}
        y={397}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={160.7}
        x={996.4}
        y={397}
      />
      <rect
        className="codecanon-letter"
        width={147.8}
        height={33.4}
        x={885.7}
        y={527.6}
      />
      <rect
        className="codecanon-letter"
        width={35.4}
        height={109.8}
        x={883.9}
        y={451.3}
      />
      <rect
        className="codecanon-letter"
        width={148.2}
        height={33.4}
        x={885.3}
        y={451.3}
      />
      <rect
        className="codecanon-diacritic"
        width={112.9}
        height={24.8}
        x={902.3}
        y={351.3}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={167.5}
        x={1049.5}
        y={393.5}
      />
      <rect
        className="codecanon-letter"
        width={148.6}
        height={36}
        x={1049.5}
        y={393.5}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={167.5}
        x={1161}
        y={393.5}
      />
      <rect
        className="codecanon-letter"
        width={148.6}
        height={36}
        x={1214.1}
        y={393.5}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={167.5}
        x={1214.1}
        y={393.5}
      />
      <rect
        className="codecanon-letter"
        width={147.3}
        height={39.1}
        x={1215.5}
        y={522}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={167.5}
        x={1325.6}
        y={393.5}
      />
      <rect
        className="codecanon-diacritic"
        width={42.3}
        height={39.8}
        x={1235.4}
        y={343.8}
      />
      <rect
        className="codecanon-diacritic"
        width={42.3}
        height={39.8}
        x={1299.3}
        y={343.8}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={167.5}
        x={1378.8}
        y={393.5}
      />
      <rect
        className="codecanon-letter"
        width={148.6}
        height={36}
        x={1378.8}
        y={393.5}
      />
      <rect
        className="codecanon-letter"
        width={37.2}
        height={167.5}
        x={1490.2}
        y={393.5}
      />
    </svg>
  )
}

export default SVGComponent
